[tool.poetry]
name = "aoc"
version = "0.1.0"
description = ""
authors = ["Pierre <pierre.git@posteo.de>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aoc-kit = "^0.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
